# Header
menu:
  Home: /
  Archives: /archives
  Tags: /tags
  Docs: /docs
  Categoies: /categories
  About: /about
  Contact: /contact
  Me: /me

# Default post title
default_post_title: Untitled

# Archive Date Format
archive_date_format: MMM YYYY


# Logo (Font Awesome Class)
fa_logo: fa-cube

# Footer About Text
footer_about: "Make Websites. Make Magic."

#Footer Copyright Line
footer_copyright: "@Untitled. All right reserved | Design & Hexo <a href=\"https://binglinli.github.io/\">Binglin Li</a>"


# Social Accounts
twitter_url: https://twitter.com/?lang=en
facebook_url: https://www.facebook.com/
instagram_url: https://www.instagram.com/
dribble_url: https://dribbble.com/
github_url: https://github.com/binglinli/hexo-theme-icehploard
googleplus_url: https://plus.google.com/
behance_url: https://www.behance.net/
fivehundredpx_url: https://500px.com/
email_url: \#
rss_url: \#

markdown:
  preset: 'default'
  render:
    html: true
    xhtmlOut: false
    langPrefix: 'language-'
    breaks: true
    linkify: true
    typographer: true
    quotes: '“”‘’'
  enable_rules:
  disable_rules:
  plugins:
  anchors:
    level: 2
    collisionSuffix: ''
    permalink: false
    permalinkClass: 'header-anchor'
    permalinkSide: 'left'
    permalinkSymbol: '¶'
    case: 0
    separator: '-'
  images:
    lazyload: false
    prepend_root: false
    post_asset: false

html_prettify:
    enable: true
    exclude:
        - "*/**/test"
    options:
        indent_size: 2
        indent_char: " "
        max_preserve_newlines: "-1"
        preserve_newlines: false
        keep_array_indentation: true
        break_chained_methods: false
        indent_scripts: normal
        brace_style: expand
        space_before_conditional: true
        unescape_strings: false
        jslint_happy: true
        end_with_newline: true
        wrap_line_length: "0"
        indent_inner_html: false
        comma_first: false
        e4x: false
        indent_empty_lines: false

easy_tags_plugin:
  enable: true
  tag_name_case: 1
  sort_ignore_case: true

restful:
  # site 可配置为数组选择性生成某些属性
  # site: ['title', 'subtitle', 'description', 'author', 'since', email', 'favicon', 'avatar']
  site: true        # hexo.config mix theme.config
  posts_size: 10    # 文章列表分页，0 表示不分页
  posts_props:      # 文章列表项的需要生成的属性
    title: true
    slug: true
    date: true
    updated: true
    comments: true
    path: true
    excerpt: false
    cover: true      # 封面图，取文章第一张图片
    content: false
    keywords: false
    categories: true
    tags: true
  categories: true         # 分类数据
  use_category_slug: false # Use slug for filename of category data
  tags: true               # 标签数据
  use_tag_slug: false      # Use slug for filename of tag data
  post: true               # 文章数据
  pages: false             # 额外的 Hexo 页面数据, 如 About

# Sitemap
sitemap:
  path: sitemap.xml

### RSS feed

# type: You can choose between Atom and RSS2
# path: the path to the rss feed
# limit: the maximum number of posts to show

feed:
  type: atom
  path: atom.xml
  limit: 10
